project:
  type: website
  output-dir: docs

website:
  title: "Josh's Data Science Blog"
  description: "This is Josh's personal Blog."
  navbar:
    search: true
    pinned: false
    collapse: false
    right:
      - text: "Home"
        file: home.qmd
      - text: "Study Note"
        file: study.qmd
      - text: "Blog"
        file: blog.qmd
    background: white
    foreground: black
format:
  html:
    css: styles.css
    toc: true
    toc-location: right
    page-layout: full
    smooth-scroll: true
    fontsize: 97%
    #linestretch: 110%
    theme:
      light: journal
      dark: [journal, theme-dark.scss]


editor: visual

